name: egohand3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - pytorch>=2.6
  - pytorch-cuda=12.1
  - pip:
      - opencv-python
      - scipy>=1.10
      - matplotlib>=3.6
      - pyrender
      - pytorch-lightning>=2.5
      - scikit-image
      - smplx==0.1.28
      - yacs
      - timm>=1.0
      - einops
      - xtcocotools
      - pandas
      - hydra-core
      - hydra-submitit-launcher
      - hydra-colorlog
      - pyrootutils
      - rich
      - webdataset
      - ultralytics==8.1.34
      - gradio
      - trimesh
      - tensorboard
