- exp_name=train_hoi4d_clean_renderegomano_half_4gpu_from_wilor_60epoch_bs120_v1
- data=hoi4d_clean_renderegomano_half
- experiment=wilor_vit_refinenet
- trainer=ddp
- trainer.strategy=ddp_find_unused_parameters_true
- trainer.devices=4
- trainer.num_nodes=1
- ckpt_path=null
- GENERAL.RESUME=False
- MODEL.PRETRAINED_CKPT=/vepfs-mlp2/mlp-public/huyaoqing/WiLoR/pretrained_models/wilor_final.ckpt
- TRAIN.BATCH_SIZE=120
- GENERAL.NUM_WORKERS=8
- GENERAL.PREFETCH_FACTOR=2
- GENERAL.LOG_STEPS=100
- GENERAL.VAL_STEPS=5000
- GENERAL.CHECKPOINT_STEPS=5000
- GENERAL.TOTAL_STEPS=86376
- GENERAL.CHECKPOINT_SAVE_TOP_K=3
